classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.ubuntu
- system.linux.system.repo.glusterfs
- system.openssh.client.lab
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_telemetry_cluster
- cluster.scale_nfv_contrail.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/sgudz/mcp11_opencontrail_dpdk"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$YTLrWWTs$aErVWnA/yuvKAUE25t9S9p48b1f/cL./jmN6eIHIKp6aL.4rI4QtyEieSDie19Og6a1uPoCc/ZE4FKuIgBP4O/"
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
            deploy_nic: enp9s0f0
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
            deploy_nic: enp11s0f0
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
          params:
            linux_system_codename: xenial
        openstack_database_node02:
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          params:
            linux_system_codename: xenial
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
        openstack_compute_node01:
          name: ${_param:openstack_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.sriov
          - cluster.${_param:cluster_name}.openstack.compute.dpdk
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node01_control_address}
            single_address: ${_param:openstack_compute_node01_single_address}
            tenant_address: ${_param:openstack_compute_node01_tenant_address}
            sriov_unsafe_interrupts: False
            compute_vrouter_dpdk_mac_address: 68:05:ca:30:03:fc
            compute_vrouter_dpdk_pci: "'0000:81:00.0'"
            primary_first_nic: ens11f0d1
            sriov_first_nic: ens11f1d1
            sriov_second_nic: ens3f0
        openstack_compute_node02:
          name: ${_param:openstack_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.sriov
          - cluster.${_param:cluster_name}.openstack.compute.dpdk
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node02_control_address}
            single_address: ${_param:openstack_compute_node02_single_address}
            tenant_address: ${_param:openstack_compute_node02_tenant_address}
            sriov_unsafe_interrupts: False
            compute_vrouter_dpdk_mac_address: 3c:fd:fe:9e:7e:30
            compute_vrouter_dpdk_pci: "'0000:81:00.0'"
            primary_first_nic: ens11f0
            sriov_first_nic: ens11f1
            sriov_second_nic: ens3f0
        # openstack_compute_rack01:
        #   name: ${_param:openstack_compute_rack01_hostname}<<count>>
        #   domain: ${_param:cluster_domain}
        #   classes:
        #   - cluster.${_param:cluster_name}.openstack.compute.sriov
        #   - cluster.${_param:cluster_name}.openstack.compute.dpdk
        #   repeat:
        #     count: 2
        #     start: 1
        #     digits: 3
        #     params:
        #       single_address:
        #         value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
        #         start: 101
        #       tenant_address:
        #         value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
        #         start: 101
        #   params:
        #     salt_master_host: ${_param:reclass_config_master}
        #     linux_system_codename: xenial
        #     sriov_nic01_device_name: eth7
        #     sriov_nic01_numvfs: 7
        #     sriov_nic01_physical_network: physnet1
        #     sriov_unsafe_interrupts: False
        #     compute_vrouter_dpdk_mac_address: 00:1b:21:87:21:99
        #     compute_vrouter_dpdk_pci: "'0000:81:00.0'"
        #     compute_vrouter_taskset: "-c 1,2"
        #     compute_vrouter_socket_mem: "1024"
